spring:
  application.name: intershop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:54332/intershop
    username: postgres
    password: postgres
server:
  port: 8040
