spring:
  liquibase:
    default-schema: shop
    change-log: classpath:liquibase/liquibase.changelog-master.xml
  application.name: intershop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://host.docker.internal:54332/intershop
    username: postgres
    password: postgres
  jpa:
    properties.hibernate.generate_statistics: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 12582912
server:
  port: 8040

