spring:
  cache:
    type: redis
  liquibase:
    url: jdbc:postgresql://host.docker.internal:54332/intershop
    user: postgres
    password: postgres
    default-schema: shop
    change-log: classpath:liquibase/liquibase.changelog-master.xml
    driver-class-name: org.postgresql.Driver
  application.name: intershop
  r2dbc:
    url: r2dbc:postgresql://host.docker.internal:54332/intershop
    username: postgres
    password: postgres
    pool:
      enabled: true
  jpa:
    properties.hibernate.generate_statistics: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 12582912
  data:
    redis:
      host: redis
      port: 6379
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8040
app:
  payment-url: "http://intershop-payment:8041"

